POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
    "email": "admin@robopipe.io",
    "password": "robopipe.io"
}

###

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc2OTg4OTE4NiwiZXhwIjoxNzY5ODkwMDg2fQ.UuieyBYS2Y0zd18UwgtzdqTL5UFNRRP9lEuuC6D3R00


POST http://localhost:3000/v1/projects
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Test Project",
    "type": "SEGMENTATION"
}

###

GET http://localhost:3000/v1/task/4
Authorization: Bearer {{accessToken}}
Content-Type: application/json