POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
    "email": "admin@robopipe.io",
    "password": "robopipe.io"
}

###

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc2OTkwNTAxNCwiZXhwIjoxNzY5OTA1OTE0fQ.TrZcWll64mfrL5GGygbU8XXwWFHXIMCQ4xBGOcR1uZc


POST http://localhost:3000/v1/projects
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Test Project 2",
    "type": "SEGMENTATION"
}

###

GET http://localhost:3000/v1/task/4
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET http://localhost:3000/v1/organizations/current
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET http://localhost:3000/v1/projects
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET http://localhost:3000/v1/projects/5
Authorization: Bearer {{accessToken}}
Content-Type: application/json
