steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
          -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/ml:${SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/ml:latest \
          -f apps/ml/Dockerfile apps/ml

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker push --all-tags ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/ml

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/ml:${SHORT_SHA} \
          --region ${_REGION} \
          --platform managed

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/ml"

options:
  logging: CLOUD_LOGGING_ONLY
