# Generated by Django 5.1.5 on 2025-02-07 14:03

import django.db.models.deletion
import nn_models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0028_auto_20241107_1031"),
    ]

    operations = [
        migrations.CreateModel(
            name="NNModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "base_model",
                    models.CharField(max_length=255, verbose_name="base_model"),
                ),
                (
                    "model_path",
                    models.CharField(max_length=255, verbose_name="model_path"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project ID for this NNModel",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nn_models",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "nn_model",
            },
            bases=(nn_models.mixins.NNModelMixin, models.Model),
        ),
    ]
