# Generated by Django 5.1.5 on 2025-02-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nn_models", "0001_initial"),
        ("projects", "0028_auto_20241107_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nnmodel",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="nnmodel",
            name="project",
            field=models.ForeignKey(
                default=3,
                help_text="Project ID for this NNModel",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nn_models",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
