# Generated by Django 5.1.5 on 2025-02-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nn_models", "0002_alter_nnmodel_name_alter_nnmodel_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="nnmodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("Generic", "Generic"),
                    ("YOLO", "YOLO"),
                    ("MobileNetSSD", "MobileNetSSD"),
                ],
                default="Generic",
                max_length=255,
                verbose_name="model_type",
            ),
            preserve_default=False,
        ),
    ]
