# Generated by Django 5.1.5 on 2025-10-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_auto_20241107_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="robopipe_api_url",
            field=models.CharField(
                blank=True,
                help_text="Robopipe API URL",
                max_length=256,
                null=True,
                verbose_name="robopipe_api_url",
            ),
        ),
    ]
