# Generated by Django 5.1.5 on 2025-11-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_project_robopipe_api_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="robopipe_api_url",
            field=models.URLField(
                blank=True,
                help_text="Robopipe API URL",
                max_length=512,
                null=True,
                verbose_name="robopipe_api_url",
            ),
        ),
    ]
