# Generated by Django 5.1.5 on 2025-11-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userproducttour"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="robopipe_api_url",
            field=models.URLField(
                default="https://robopipe-1.local",
                help_text="Robopipe API URL",
                max_length=512,
                verbose_name="Robopipe API URL",
            ),
        ),
    ]
